// Enhanced Black Market Tools Data
const toolsData = [
    { name: 'Rubber Ducky V2', desc: 'Keystroke injection tool. Bypass endpoint protection.', price: '$49.99', img: 'assets/offensive.png' },
    { name: 'WiFi Pineapple', desc: 'Rogue Access Point for MITM attacks.', price: '$119.99', img: 'assets/networking.png' },
    { name: 'Flipper Zero', desc: 'Multi-tool for hardware hacking & pentesting.', price: '$169.00', img: 'assets/offensive.png' },
    { name: 'Burp Suite Pro', desc: '1 Year License. Web application security testing.', price: '$399.00', img: 'assets/academy.png' },
    { name: 'Pentest Laptop (Refurb)', desc: 'Pre-loaded with Kali Linux. i7, 32GB RAM, 1TB SSD.', price: '$850.00', img: 'assets/networking.png' },
    { name: 'Proxmark3 RDV4', desc: 'RFID cloning & analysis tool for physical access.', price: '$289.00', img: 'assets/offensive.png' },
    { name: 'HackRF One', desc: 'Software Defined Radio (SDR) 1MHz-6GHz.', price: '$349.00', img: 'assets/networking.png' },
    { name: 'Alfa AWUS036ACH', desc: 'High-power WiFi adapter for packet injection.', price: '$39.99', img: 'assets/networking.png' },
    { name: 'LAN Turtle', desc: 'Covert penetration testing tool in RJ45 form factor.', price: '$59.99', img: 'assets/offensive.png' },
    { name: 'Bash Bunny', desc: 'Multi-attack USB automation platform.', price: '$99.99', img: 'assets/offensive.png' },
    { name: 'Packet Squirrel', desc: 'Remote access & packet capturing device.', price: '$79.99', img: 'assets/networking.png' },
    { name: 'Screen Crab', desc: 'HDMI man-in-the-middle for video interception.', price: '$99.00', img: 'assets/offensive.png' },
    { name: 'Metasploit Pro', desc: 'Enterprise penetration testing framework (1 year).', price: '$15,000', img: 'assets/academy.png' },
    { name: 'Cobalt Strike', desc: 'Adversary simulation & red team operations.', price: '$5,900', img: 'assets/offensive.png' },
    { name: 'Tenable Nessus Pro', desc: 'Vulnerability scanner with advanced reporting.', price: '$3,990', img: 'assets/defensive.png' },
    { name: 'PortSwigger Intruder', desc: 'Automated attack toolkit (Burp extension).', price: '$99.00', img: 'assets/offensive.png' },
    { name: 'WiFi Deauther', desc: 'ESP8266 deauthentication attack device.', price: '$19.99', img: 'assets/networking.png' },
    { name: 'USB Killer V4', desc: 'High-voltage USB device destructor (For Testing Only).', price: '$59.00', img: 'assets/offensive.png' },
    { name: 'Raspberry Pi 4 (8GB)', desc: 'Portable hacking station with Kali Linux.', price: '$75.00', img: 'assets/networking.png' },
    { name: 'Chameleon Mini', desc: 'RFID emulation & cloning toolkit.', price: '$119.00', img: 'assets/offensive.png' },
    { name: 'Key Grabber', desc: 'Hardware keylogger with 16GB storage.', price: '$49.00', img: 'assets/offensive.png' },
    { name: 'ESPKey', desc: 'Wireless keyboard injection attack tool.', price: '$29.99', img: 'assets/networking.png' },
    { name: 'Throwing Star LAN Tap', desc: 'Passive network tap for traffic monitoring.', price: '$15.99', img: 'assets/networking.png' },
    { name: 'O.MG Cable', desc: 'Implanted malicious USB cable for remote access.', price: '$179.00', img: 'assets/offensive.png' },
    { name: 'Lock Pick Set (24pc)', desc: 'Professional lock picking & bypass tools.', price: '$39.99', img: 'assets/offensive.png' },
    { name: 'YARD Stick One', desc: 'Sub-1GHz RF transceiver for IoT attacks.', price: '$99.00', img: 'assets/networking.png' },
    { name: 'BladeRF 2.0', desc: 'Software Defined Radio for advanced attacks.', price: '$719.00', img: 'assets/networking.png' },
    { name: 'Pwnie Express', desc: 'Pen Test Drop Box with cellular backup.', price: '$1,295', img: 'assets/offensive.png' },
    { name: 'WiFi Coconut', desc: '14 WiFi radio sniffer for wireless analysis.', price: '$99.00', img: 'assets/networking.png' },
    { name: 'Crazyradio PA', desc: '2.4GHz USB radio for drone/keyboard hacking.', price: '$29.99', img: 'assets/networking.png' },
    { name: 'RTLSDR Blog V4', desc: 'Affordable SDR dongle (500kHz-1.7GHz).', price: '$44.95', img: 'assets/networking.png' },
    { name: 'Red Pitaya', desc: 'Open-source test equipment for signal analysis.', price: '$499.00', img: 'assets/networking.png' },
    { name: 'Ubertooth One', desc: 'Bluetooth analysis & exploitation device.', price: '$124.99', img: 'assets/networking.png' },
    { name: 'Hak5 Signal Owl', desc: 'Cellular toolkit for remote pentesting.', price: '$99.00', img: 'assets/offensive.png' },
    { name: 'NFC Killerbee', desc: 'NFC reader/writer for access control bypass.', price: '$199.00', img: 'assets/offensive.png' },
    { name: 'Kali Linux ARM SBC', desc: 'Single Board Computer with pre-installed Kali.', price: '$89.00', img: 'assets/networking.png' },
    { name: 'Network TAP Gigabit', desc: 'High-speed network traffic analyzer.', price: '$199.00', img: 'assets/networking.png' },
    { name: 'Malduino Elite', desc: 'Arduino-based USB attack platform.', price: '$44.99', img: 'assets/offensive.png' },
    { name: 'Digispark Kickstarter', desc: 'Tiny USB development board for attacks.', price: '$8.99', img: 'assets/offensive.png' },
    { name: 'P4wnP1 A.L.O.A.', desc: 'Raspberry Pi Zero W hacking framework.', price: '$35.00', img: 'assets/offensive.png' },
    { name: 'Deauth Detector', desc: 'WiFi deauth attack detection device.', price: '$24.99', img: 'assets/defensive.png' },
    { name: 'Poisontap', desc: 'Raspberry Pi Zero backdoor installer.', price: '$29.00', img: 'assets/offensive.png' },
    { name: 'WiFi Jammer Pro', desc: '2.4GHz/5GHz dual-band jammer (Legal Use Only).', price: '$149.99', img: 'assets/offensive.png' },
    { name: 'Ghost ESP', desc: 'Portable WiFi/Bluetooth attack toolkit.', price: '$39.99', img: 'assets/offensive.png' },
    { name: 'Screen Capture HDMI', desc: 'Live video interception & recording device.', price: '$89.00', img: 'assets/offensive.png' },
    { name: 'USB Condom', desc: 'Data blocker for safe charging in public.', price: '$9.99', img: 'assets/defensive.png' },
    { name: 'Faraday Bag', desc: 'RF-blocking bag for mobile forensics.', price: '$29.99', img: 'assets/defensive.png' },
    { name: 'Anti-Spy Camera Finder', desc: 'Detect hidden cameras & listening devices.', price: '$79.99', img: 'assets/defensive.png' },
    { name: 'Hardware Wallet Ledger', desc: 'Secure cryptocurrency cold storage.', price: '$79.00', img: 'assets/defensive.png' },
    { name: 'YubiKey 5 NFC', desc: 'Multi-protocol security key for 2FA.', price: '$49.00', img: 'assets/defensive.png' }
];

// Enhanced Courses Data
const coursesData = [
    { title: 'Ethical Hacking Zero to Hero', level: 'BEGINNER', price: '$49.99', desc: 'Complete introduction to Linux, Python, and Basic Exploits.', img: 'assets/academy.png' },
    { title: 'Network Penetration Testing', level: 'INTERMEDIATE', price: '$89.99', desc: 'Master Nmap, Metasploit, Active Directory attacks, and Pivoting.', img: 'assets/defensive.png' },
    { title: 'Red Team & Logic Bugs', level: 'EXPERT', price: '$149.99', desc: 'Advanced evasion, custom payload development, and enterprise hacking.', img: 'assets/offensive.png' },
    { title: 'Web Application Security', level: 'INTERMEDIATE', price: '$79.99', desc: 'OWASP Top 10, SQLi, XSS, CSRF, and modern web vulnerabilities.', img: 'assets/offensive.png' },
    { title: 'Mobile App Pentesting', level: 'INTERMEDIATE', price: '$99.99', desc: 'Android & iOS security testing with Frida and Objection.', img: 'assets/offensive.png' },
    { title: 'Bug Bounty Hunter Bootcamp', level: 'INTERMEDIATE', price: '$129.99', desc: 'From recon to reporting on HackerOne and Bugcrowd.', img: 'assets/offensive.png' },
    { title: 'OSINT & Reconnaissance', level: 'BEGINNER', price: '$39.99', desc: 'Open Source Intelligence Gathering with Maltego, Shodan, and Recon-ng.', img: 'assets/osint.png' },
    { title: 'Wireless Network Hacking', level: 'INTERMEDIATE', price: '$69.99', desc: 'WiFi cracking, evil twin attacks, and WPA3 bypass techniques.', img: 'assets/networking.png' },
    { title: 'Cloud Security (AWS/Azure)', level: 'INTERMEDIATE', price: '$109.99', desc: 'Cloud pentesting, misconfigurations, and IAM exploitation.', img: 'assets/defensive.png' },
    { title: 'Social Engineering Tactics', level: 'BEGINNER', price: '$44.99', desc: 'Phishing, vishing, pretexting, and physical security bypass.', img: 'assets/offensive.png' },
    { title: 'Malware Analysis & Reverse Engineering', level: 'EXPERT', price: '$199.99', desc: 'Disassembly, debugging, and understanding malicious code.', img: 'assets/offensive.png' },
    { title: 'Active Directory Exploitation', level: 'EXPERT', price: '$159.99', desc: 'Kerberoasting, Golden Tickets, and domain compromise.', img: 'assets/offensive.png' },
    { title: 'Linux Privilege Escalation', level: 'INTERMEDIATE', price: '$59.99', desc: 'Kernel exploits, SUID binaries, and escape techniques.', img: 'assets/offensive.png' },
    { title: 'Windows Privilege Escalation', level: 'INTERMEDIATE', price: '$59.99', desc: 'UAC bypass, DLL hijacking, and service exploitation.', img: 'assets/offensive.png' },
    { title: 'Python for Hackers', level: 'BEGINNER', price: '$34.99', desc: 'Scripting for automation, exploit development, and tool creation.', img: 'assets/academy.png' },
    { title: 'Bash Scripting for Pentesting', level: 'BEGINNER', price: '$29.99', desc: 'Automate reconnaissance and post-exploitation tasks.', img: 'assets/academy.png' },
    { title: 'Buffer Overflow Exploitation', level: 'EXPERT', price: '$179.99', desc: 'Stack & heap overflows with DEP/ASLR bypass.', img: 'assets/offensive.png' },
    { title: 'Docker & Kubernetes Security', level: 'INTERMEDIATE', price: '$89.99', desc: 'Container escape, registry attacks, and orchestration flaws.', img: 'assets/defensive.png' },
    { title: 'API Security Testing', level: 'INTERMEDIATE', price: '$74.99', desc: 'REST/GraphQL vulnerabilities and authentication bypass.', img: 'assets/offensive.png' },
    { title: 'Forensics & Incident Response', level: 'INTERMEDIATE', price: '$99.99', desc: 'Memory analysis, disk forensics, and threat hunting.', img: 'assets/defensive.png' },
    { title: 'Cryptography & Encryption Breaking', level: 'EXPERT', price: '$139.99', desc: 'Understanding crypto weaknesses and implementation flaws.', img: 'assets/offensive.png' },
    { title: 'IoT Device Hacking', level: 'INTERMEDIATE', price: '$79.99', desc: 'Firmware extraction, UART debugging, and hardware attacks.', img: 'assets/offensive.png' },
    { title: 'Automotive Security', level: 'EXPERT', price: '$249.99', desc: 'CAN bus hacking, keyless entry bypass, and ECU exploitation.', img: 'assets/offensive.png' },
    { title: 'SCADA & ICS Security', level: 'EXPERT', price: '$299.99', desc: 'Industrial control systems and critical infrastructure hacking.', img: 'assets/offensive.png' },
    { title: 'Physical Security & Lockpicking', level: 'BEGINNER', price: '$39.99', desc: 'Lock bypass, tailgating, and social engineering physical access.', img: 'assets/offensive.png' },
    { title: 'Threat Intelligence Analysis', level: 'INTERMEDIATE', price: '$89.99', desc: 'IOCs, APT tracking, and predictive security analysis.', img: 'assets/defensive.png' },
    { title: 'SOC Analyst Training', level: 'BEGINNER', price: '$69.99', desc: 'SIEM, log analysis, and security monitoring foundations.', img: 'assets/defensive.png' },
    { title: 'Blue Team Defense Strategies', level: 'INTERMEDIATE', price: '$99.99', desc: 'Hardening, detection, and incident response procedures.', img: 'assets/defensive.png' },
    { title: 'CompTIA Security+ Prep', level: 'BEGINNER', price: '$59.99', desc: 'Certification preparation with hands-on labs.', img: 'assets/academy.png' },
    { title: 'CEH (Certified Ethical Hacker)', level: 'INTERMEDIATE', price: '$199.99', desc: 'Official EC-Council training materials and exam prep.', img: 'assets/academy.png' },
    { title: 'OSCP Exam Preparation', level: 'EXPERT', price: '$299.99', desc: 'Offensive Security PWK bootcamp with lab access.', img: 'assets/academy.png' },
    { title: 'CISSP Complete Guide', level: 'EXPERT', price: '$249.99', desc: 'Security management and architecture certification.', img: 'assets/academy.png' },
    { title: 'AWS Security Specialty', level: 'INTERMEDIATE', price: '$89.99', desc: 'Cloud security certification preparation.', img: 'assets/academy.png' },
    { title: 'GRC (Governance, Risk, Compliance)', level: 'INTERMEDIATE', price: '$79.99', desc: 'Policy creation, risk assessment, and audit preparation.', img: 'assets/defensive.png' },
    { title: 'Threat Modeling', level: 'INTERMEDIATE', price: '$69.99', desc: 'STRIDE, DREAD, and attack tree methodologies.', img: 'assets/defensive.png' },
    { title: 'Zero Trust Architecture', level: 'EXPERT', price: '$159.99', desc: 'Modern security model implementation.', img: 'assets/defensive.png' },
    { title: 'DevSecOps Pipeline', level: 'INTERMEDIATE', price: '$89.99', desc: 'CI/CD security integration and automated testing.', img: 'assets/defensive.png' },
    { title: 'Purple Team Operations', level: 'EXPERT', price: '$179.99', desc: 'Combined offensive and defensive security exercises.', img: 'assets/offensive.png' },
    { title: 'Ransomware Defense', level: 'INTERMEDIATE', price: '$99.99', desc: 'Detection, prevention, and recovery strategies.', img: 'assets/defensive.png' },
    { title: 'Phishing Simulation & Training', level: 'BEGINNER', price: '$44.99', desc: 'Build awareness campaigns and test user resilience.', img: 'assets/defensive.png' },
    { title: 'Secure Code Review', level: 'INTERMEDIATE', price: '$89.99', desc: 'Static analysis and vulnerability detection in source code.', img: 'assets/defensive.png' },
    { title: 'Web3 & Blockchain Security', level: 'EXPERT', price: '$199.99', desc: 'Smart contract auditing and DeFi exploitation.', img: 'assets/offensive.png' },
    { title: 'AI/ML Security', level: 'EXPERT', price: '$179.99', desc: 'Adversarial attacks, model poisoning, and privacy.', img: 'assets/offensive.png' },
    { title: 'Darkweb OSINT', level: 'INTERMEDIATE', price: '$69.99', desc: 'Tor, I2P, and underground marketplace intelligence.', img: 'assets/osint.png' },
    { title: '5G Network Security', level: 'EXPERT', price: '$249.99', desc: 'Next-gen mobile network vulnerabilities.', img: 'assets/networking.png' },
    { title: 'Quantum Cryptography', level: 'EXPERT', price: '$299.99', desc: 'Post-quantum security and future-proof encryption.', img: 'assets/academy.png' },
    { title: 'Privacy Engineering', level: 'INTERMEDIATE', price: '$79.99', desc: 'GDPR, data minimization, and anonymization techniques.', img: 'assets/defensive.png' },
    { title: 'CTF Master Class', level: 'INTERMEDIATE', price: '$59.99', desc: 'Capture The Flag competition strategies and writeups.', img: 'assets/offensive.png' },
    { title: 'Binary Exploitation', level: 'EXPERT', price: '$219.99', desc: 'Advanced exploit development and shellcoding.', img: 'assets/offensive.png' },
    { title: 'Game Hacking', level: 'INTERMEDIATE', price: '$69.99', desc: 'Memory editing, cheat development, and anti-cheat bypass.', img: 'assets/offensive.png' }
];
